name: Release

on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
    - name: Get major version
      id: get_major_version
      uses: mavrosxristoforos/get-xml-info@2.0
      with:
        xml-file: './GlobalAssemblyInfo.csproj'
        xpath: '//MajorVersion'
    - name: Get minor version
      id: get_minor_version
      uses: mavrosxristoforos/get-xml-info@2.0
      with:
        xml-file: './GlobalAssemblyInfo.csproj'
        xpath: '//MinorVersion'
    - name: Get build number
      id: get_build_number
      env:
        major: ${{ steps.get_major_version.outputs.info }}
        minor: ${{ steps.get_minor_version.outputs.info }}
      run: |
        $build_number=(.\get-build-number.ps1 $Env:major $Env:minor)
        echo "build_number=${build_number}" >> $Env:GITHUB_OUTPUT
    - name: Restore
      run: dotnet restore ./EPMinus.sln
    - name: Build
      run: >
        dotnet build
        -c Release
        --no-restore
        -p:BuildNumber=${{ steps.get_build_number.outputs.build_number }}
        ./EPMinus.sln
    - name: Test
      run: >
        dotnet test
        -c Release
        --no-restore
        --no-build
        ./EPMinus.sln
    - name: Pack
      run: >
        dotnet pack
        -c Release
        --no-restore
        --no-build
        -p:BuildNumber=${{ steps.get_build_number.outputs.build_number }}
        ./EPPlus/EPPlus.csproj
    - name: Push package
      run: >
       dotnet nuget push
       .\EPPlus\bin\Release\*.nupkg
       -k ${{ env.GITHUB_TOKEN }}
       -s https://nuget.pkg.github.com/StuYarrow/index.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Tag repo with version
      uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: v${{ steps.get_major_version.outputs.info }}.${{ steps.get_minor_version.outputs.info }}.${{ steps.get_build_number.outputs.build_number }}
